created structured cldf dataset out of Postgres DB
cldf-datasets/nts pull request #1
Opened 2021-01-28 10:57 UTC by Bibiko

2021-01-28 14:13 UTC, xrotwang requested changes
See comments.

2021-01-28 14:13 UTC, xrotwang commented on CONTRIBUTORS.md
> +Harald Hammarström |  | Editor | Author
I think we should list all names of the citation as authors - in proper order.

2021-01-28 14:13 UTC, xrotwang commented on metadata.json
> +    "license": "http://creativecommons.org/licenses/by-nc-nd/2.0/de/deed.en",
We should drop the "ND" clause, because Grambank is - to some extent - derived from NTS.

2021-01-29 09:22 UTC, Bibiko commented on metadata.json
> +    "license": "http://creativecommons.org/licenses/by-nc-nd/2.0/de/deed.en",
Do we have permission from the authors to change the copyright?

2021-01-29 09:48 UTC, xrotwang commented on metadata.json
> +    "license": "http://creativecommons.org/licenses/by-nc-nd/2.0/de/deed.en",
Not explicitly. But given the fact that Grambank is derived (partly) from NTS, and most of the NTS people are also behind Grambank, I'd assume they'd be ok with that.

2021-01-29 12:38 UTC, xrotwang approved these changes

2021-01-29 12:38 UTC, merged